## Numpy

In [8]:
import numpy as np

In [10]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [13]:
np.array([1,2,3,4,5])+10

array([11, 12, 13, 14, 15])

In [15]:
np.array([1,2,3,4,5]).shape

(5,)

In [17]:
np.array([[1,2,3,4],[6,7,8,9]]).shape

(2, 4)

In [19]:
np.array([[1,2,3,4],[6,7,8,9]])[0]

array([1, 2, 3, 4])

In [21]:
np.array([[1,2,3,4],[6,7,8,9]])[0][2]

3

## Pandas

In [23]:
import pandas as pd

In [29]:
# Creación de series
sr = pd.Series([10,9,8,7,6])

In [30]:
sr.values

array([10,  9,  8,  7,  6], dtype=int64)

In [31]:
# Estructura de la serie
sr.index

RangeIndex(start=0, stop=5, step=1)

In [32]:
# Forma de la serie
sr.shape

(5,)

In [34]:
# Consulta de datos
sr[3]

7

In [35]:
sr[[0,4,2]]

0    10
4     6
2     8
dtype: int64

In [36]:
# Renombrar los indices
sr = pd.Series([10,9,8,7,6], index=['a','b','c','d','e'])

In [37]:
sr

a    10
b     9
c     8
d     7
e     6
dtype: int64

In [38]:
sr['c']

8

In [39]:
# Selección múltiple
sr[['c','d','e']]

c    8
d    7
e    6
dtype: int64

In [41]:
# Selección por rangos
sr['b':'e']

b    9
c    8
d    7
e    6
dtype: int64

In [45]:
# Diccionarios
data = {'CO':100, 'MX':200, 'AR':300}
data

{'CO': 100, 'MX': 200, 'AR': 300}

In [46]:
data.keys()

dict_keys(['CO', 'MX', 'AR'])

In [47]:
data['MX']

200

In [48]:
# Convertir un diccionario a una serie
pd.Series(data)

CO    100
MX    200
AR    300
dtype: int64

In [49]:
pd.Series(data, index=['CO', 'MX', 'PE'])

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [50]:
# Uso de valores nulos, las operaciones no afectan el resultado, siempre es nulo
import numpy as np
np.nan

nan

In [51]:
np.nan +10

nan

In [52]:
np. nan * 10

nan

In [53]:
sr = pd.Series(data, index=['CO', 'MX', 'PE'])

In [54]:
sr

CO    100.0
MX    200.0
PE      NaN
dtype: float64

In [55]:
sr.isnull()

CO    False
MX    False
PE     True
dtype: bool

In [56]:
sr.notnull()

CO     True
MX     True
PE    False
dtype: bool