## Concatenación de DataFrames

In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:.2f}'.format

In [3]:
np.set_printoptions(precision=2)

In [7]:
x1 = np.random.rand(2,5)*100
x1

array([[ 1.61, 34.58, 40.62, 28.65, 79.58],
       [88.81,  9.35, 42.93, 38.65, 43.27]])

In [8]:
x2 = np.random.rand(2,5)*-1
x2

array([[-0.86, -0.17, -0.96, -0.47, -0.1 ],
       [-0.21, -0.24, -0.65, -0.62, -0.5 ]])

In [9]:
np.concatenate([x1,x2])

array([[ 1.61, 34.58, 40.62, 28.65, 79.58],
       [88.81,  9.35, 42.93, 38.65, 43.27],
       [-0.86, -0.17, -0.96, -0.47, -0.1 ],
       [-0.21, -0.24, -0.65, -0.62, -0.5 ]])

In [11]:
np.concatenate([x1,x2]).shape

(4, 5)

In [10]:
np.concatenate([x1,x2], axis = 1)

array([[ 1.61, 34.58, 40.62, 28.65, 79.58, -0.86, -0.17, -0.96, -0.47,
        -0.1 ],
       [88.81,  9.35, 42.93, 38.65, 43.27, -0.21, -0.24, -0.65, -0.62,
        -0.5 ]])

In [12]:
np.concatenate([x1,x2], axis = 1).shape

(2, 10)

In [14]:
s1 = pd.Series(x1[0], index=['a','b','c','d','e'])
s1

a    1.61
b   34.58
c   40.62
d   28.65
e   79.58
dtype: float64

In [16]:
s2 = pd.Series(x2[0], index=['c','d','e','f','g'])
s2

c   -0.86
d   -0.17
e   -0.96
f   -0.47
g   -0.10
dtype: float64

In [17]:
pd.concat([s1,s2])

a    1.61
b   34.58
c   40.62
d   28.65
e   79.58
c   -0.86
d   -0.17
e   -0.96
f   -0.47
g   -0.10
dtype: float64

In [18]:
pd.concat([s1,s2], axis=1)

0     1
a  1.61   nan
b 34.58   nan
c 40.62 -0.86
d 28.65 -0.17
e 79.58 -0.96
f   nan -0.47
g   nan -0.10

In [19]:
s1.reset_index(drop=True)

0    1.61
1   34.58
2   40.62
3   28.65
4   79.58
dtype: float64

In [20]:
pd.concat([s1.reset_index(drop=True),s2.reset_index(drop=True)], axis=1)

0     1
0  1.61 -0.86
1 34.58 -0.17
2 40.62 -0.96
3 28.65 -0.47
4 79.58 -0.10

In [23]:
df1 = pd.DataFrame(np.random.rand(3,2)*10, columns=['a','b'])
df1

a    b
0 6.27 9.12
1 8.77 1.05
2 1.10 9.65

In [24]:
df2 = pd.DataFrame(np.random.rand(3,2)*-1, columns=['a','b'])
df2

a     b
0 -0.93 -0.21
1 -0.63 -0.08
2 -0.87 -0.50

In [25]:
pd.concat([df1,df2])

a     b
0  6.27  9.12
1  8.77  1.05
2  1.10  9.65
0 -0.93 -0.21
1 -0.63 -0.08
2 -0.87 -0.50

In [26]:
pd.concat([df1,df2], axis=1)

a    b     a     b
0 6.27 9.12 -0.93 -0.21
1 8.77 1.05 -0.63 -0.08
2 1.10 9.65 -0.87 -0.50

In [29]:
pd.concat([df1,df2], axis=1, join='inner')

a    b     a     b
0 6.27 9.12 -0.93 -0.21
1 8.77 1.05 -0.63 -0.08
2 1.10 9.65 -0.87 -0.50

In [30]:
pd.concat([df1.reset_index(drop=True),df2.reset_index(drop=True)], axis=1, join='inner')

a    b     a     b
0 6.27 9.12 -0.93 -0.21
1 8.77 1.05 -0.63 -0.08
2 1.10 9.65 -0.87 -0.50

In [33]:
df1.append(df2).append(df2)

a     b
0  6.27  9.12
1  8.77  1.05
2  1.10  9.65
0 -0.93 -0.21
1 -0.63 -0.08
2 -0.87 -0.50
0 -0.93 -0.21
1 -0.63 -0.08
2 -0.87 -0.50

In [34]:
df1.T.append(df2.T)

0     1     2
a  6.27  8.77  1.10
b  9.12  1.05  9.65
a -0.93 -0.63 -0.87
b -0.21 -0.08 -0.50